dist: xenial
language: node_js
before_install:
  - sudo apt-get install -y build-essential libuv1
cache: false

jobs:
    include:
    - stage: build-locally
      script: npm install --build-from-source
      name: "Build on node 8"
      node_js: "8"
    - script: npm install --build-from-source
      name: "Build on node 10"
      node_js: "10"
